        location ~ [^/]\.php(/|$)
        {
            fastcgi_pass  unix:/usr/local/php/var/run/php-fpm.sock;
            fastcgi_index index.php;
            include fastcgi.conf;
            include pathinfo.conf;
        }
